// src/App.tsx
import { useCallback, useEffect, useMemo, useState } from 'react'
import type { Database } from 'sql.js'
import './App.css'
import { DictionaryView } from './components/DictionaryView'
import { LearnView } from './components/LearnView'
import { ProgressBrowseView } from './components/ProgressBrowseView'
import { UploadScreen } from './components/UploadScreen'
import { DataMenu } from './components/DataMenu'
import { ProgressProvider, useProgress } from './context/ProgressContext'
import { IDB_KEYS, ensureBackupCacheMigrated, idbGet, idbPut } from './lib/backupIdb'
import { loadProgress } from './lib/progressStorage'
import { listCategoryStats, openRewordDatabase } from './db/rewordDb'

type Tab = 'dictionary' | 'learn' | 'repeat' | 'learned' | 'newWords'

export default function App() {
  return (
    <ProgressProvider>
      <AppInner />
    </ProgressProvider>
  )
}

function AppInner() {
  const { importFromRewordBackupDb } = useProgress()
  const [db, setDb] = useState<Database | null>(null)
  const [backupBuffer, setBackupBuffer] = useState<ArrayBuffer | null>(null)
  const [busy, setBusy] = useState(false)
  const [hydrating, setHydrating] = useState(true)
  const [err, setErr] = useState<string | null>(null)
  const [tab, setTab] = useState<Tab>('dictionary')
  const [selectedCategoryId, setSelectedCategoryId] = useState<string | null>(null)

  useEffect(() => {
    void (async () => {
      try {
        await ensureBackupCacheMigrated()
        const buf = await idbGet<ArrayBuffer>(IDB_KEYS.backupBuffer)
        if (!buf) {
          setHydrating(false)
          return
        }
        const database = await openRewordDatabase(buf)
        setBackupBuffer(buf)
        setDb(database)
      } catch (e) {
        setErr(e instanceof Error ? e.message : String(e))
      } finally {
        setHydrating(false)
      }
    })()
  }, [])

  /** Первый запуск: переносим прогресс из таблицы WORD файла бэкапа в локальный SRS (иначе прогресс в браузере остаётся пустым). */
  useEffect(() => {
    if (!db) return
    const snap = loadProgress()
    if (Object.keys(snap.words).length > 0) return
    importFromRewordBackupDb(db, 'mergeOverwrite')
  }, [db, importFromRewordBackupDb])

  const categories = useMemo(() => (db ? listCategoryStats(db) : []), [db])

  const handlePick = async (file: File) => {
    setBusy(true)
    setErr(null)
    try {
      const buf = await file.arrayBuffer()
      await idbPut(IDB_KEYS.backupBuffer, buf)
      await idbPut(IDB_KEYS.backupMeta, { name: file.name, savedAt: Date.now() })
      const database = await openRewordDatabase(buf)
      setBackupBuffer(buf)
      setDb(database)
    } catch (e) {
      setErr(e instanceof Error ? e.message : String(e))
    } finally {
      setBusy(false)
    }
  }

  const replaceBackup = useCallback(async (buffer: ArrayBuffer, meta: { name: string }) => {
    await idbPut(IDB_KEYS.backupBuffer, buffer)
    await idbPut(IDB_KEYS.backupMeta, { ...meta, savedAt: Date.now() })
    const database = await openRewordDatabase(buffer)
    setBackupBuffer(buffer)
    setDb(database)
  }, [])

  if (hydrating) {
    return (
      <div className="upload-screen">
        <div className="upload-card">
          <div className="muted">Загрузка кэша словаря из браузера…</div>
        </div>
      </div>
    )
  }

  if (!db) return <UploadScreen busy={busy} error={err} onPick={handlePick} />

  return (
    <div className="app">
      <header className="topbar">
        <nav className="tabs" aria-label="Разделы">
          <button type="button" className={tab === 'dictionary' ? 'active' : ''} onClick={() => setTab('dictionary')}>
            Словарь
          </button>
          <button type="button" className={tab === 'learn' ? 'active' : ''} onClick={() => setTab('learn')}>
            Учить
          </button>
          <button type="button" className={tab === 'repeat' ? 'active' : ''} onClick={() => setTab('repeat')}>
            Повторение
          </button>
          <button type="button" className={tab === 'learned' ? 'active' : ''} onClick={() => setTab('learned')}>
            Изученное
          </button>
          <button type="button" className={tab === 'newWords' ? 'active' : ''} onClick={() => setTab('newWords')}>
            Новое
          </button>
        </nav>
        <div className="topbar-right">
          <DataMenu backupBuffer={backupBuffer} onReplaceBackup={replaceBackup} />
        </div>
      </header>

      <main className="main">
        {tab === 'dictionary' ? (
          <DictionaryView
            db={db}
            categories={categories}
            selectedId={selectedCategoryId}
            onSelectCategory={setSelectedCategoryId}
          />
        ) : tab === 'learn' ? (
          <LearnView db={db} activeCategoryId={selectedCategoryId} />
        ) : tab === 'repeat' ? (
          <ProgressBrowseView db={db} mode="due_now" activeCategoryId={selectedCategoryId} />
        ) : tab === 'learned' ? (
          <ProgressBrowseView db={db} mode="learned_review" activeCategoryId={selectedCategoryId} />
        ) : (
          <ProgressBrowseView db={db} mode="new_words" activeCategoryId={selectedCategoryId} />
        )}
      </main>
    </div>
  )
}

// src/App.vue
<script setup lang="ts">
import type { Database } from 'sql.js'
import { computed, onMounted, ref, watch } from 'vue'
import './App.css'
import DictionaryView from './components/DictionaryView.vue'
import LearnView from './components/LearnView.vue'
import ProgressBrowseView from './components/ProgressBrowseView.vue'
import UploadScreen from './components/UploadScreen.vue'
import DataMenu from './components/DataMenu.vue'
import GroqUsageBadge from './components/GroqUsageBadge.vue'
import { IDB_KEYS, ensureBackupCacheMigrated, idbGet, idbPut } from './lib/backupIdb'
import { loadProgress } from './lib/progressStorage'
import { listCategoryStats, openRewordDatabase } from './db/rewordDb'
import { useProgressStore } from './stores/progress'

type Tab = 'dictionary' | 'learn' | 'repeat' | 'learned' | 'newWords'

const progress = useProgressStore()

const db = ref<Database | null>(null)
const backupBuffer = ref<ArrayBuffer | null>(null)
const busy = ref(false)
const hydrating = ref(true)
const err = ref<string | null>(null)
const tab = ref<Tab>('dictionary')
const selectedCategoryId = ref<string | null>(null)

onMounted(() => {
  void (async () => {
    try {
      await ensureBackupCacheMigrated()
      const buf = await idbGet<ArrayBuffer>(IDB_KEYS.backupBuffer)
      if (!buf) {
        hydrating.value = false
        return
      }
      const database = await openRewordDatabase(buf)
      backupBuffer.value = buf
      db.value = database
    } catch (e) {
      err.value = e instanceof Error ? e.message : String(e)
    } finally {
      hydrating.value = false
    }
  })()
})

watch(db, (d) => {
  if (!d) return
  const snap = loadProgress()
  if (Object.keys(snap.words).length > 0) return
  progress.importFromRewordBackupDb(d, 'mergeOverwrite')
})

const categories = computed(() => (db.value ? listCategoryStats(db.value) : []))

async function handlePick(file: File) {
  busy.value = true
  err.value = null
  try {
    const buf = await file.arrayBuffer()
    await idbPut(IDB_KEYS.backupBuffer, buf)
    await idbPut(IDB_KEYS.backupMeta, { name: file.name, savedAt: Date.now() })
    const database = await openRewordDatabase(buf)
    backupBuffer.value = buf
    db.value = database
  } catch (e) {
    err.value = e instanceof Error ? e.message : String(e)
  } finally {
    busy.value = false
  }
}

async function replaceBackup(buffer: ArrayBuffer, meta: { name: string }) {
  await idbPut(IDB_KEYS.backupBuffer, buffer)
  await idbPut(IDB_KEYS.backupMeta, { ...meta, savedAt: Date.now() })
  const database = await openRewordDatabase(buffer)
  backupBuffer.value = buffer
  db.value = database
}
</script>

<template>
  <div v-if="hydrating" class="upload-screen">
    <div class="upload-card">
      <div class="muted">Загрузка кэша словаря из браузера…</div>
    </div>
  </div>

  <UploadScreen v-else-if="!db" :busy="busy" :error="err" @pick="handlePick" />

  <div v-else class="app">
    <header class="topbar">
      <nav class="tabs" aria-label="Разделы">
        <button type="button" :class="{ active: tab === 'dictionary' }" @click="tab = 'dictionary'">Словарь</button>
        <button type="button" :class="{ active: tab === 'learn' }" @click="tab = 'learn'">Учить</button>
        <button type="button" :class="{ active: tab === 'repeat' }" @click="tab = 'repeat'">Повторение</button>
        <button type="button" :class="{ active: tab === 'learned' }" @click="tab = 'learned'">Изученное</button>
        <button type="button" :class="{ active: tab === 'newWords' }" @click="tab = 'newWords'">Новое</button>
      </nav>
      <div class="topbar-right">
        <GroqUsageBadge />
        <DataMenu :db="db" :backup-buffer="backupBuffer" :on-replace-backup="replaceBackup" />
      </div>
    </header>

    <main class="main">
      <DictionaryView
        v-if="tab === 'dictionary'"
        :db="db"
        :categories="categories"
        :selected-id="selectedCategoryId"
        @select-category="selectedCategoryId = $event"
      />
      <LearnView v-else-if="tab === 'learn'" :db="db" :active-category-id="selectedCategoryId" />
      <ProgressBrowseView
        v-else-if="tab === 'repeat'"
        :db="db"
        mode="due_now"
        :active-category-id="selectedCategoryId"
      />
      <ProgressBrowseView
        v-else-if="tab === 'learned'"
        :db="db"
        mode="learned_review"
        :active-category-id="selectedCategoryId"
      />
      <ProgressBrowseView v-else :db="db" mode="new_words" :active-category-id="selectedCategoryId" />
    </main>
  </div>
</template>
